language: julia
os:
    - linux
julia:
    - 0.6
    - nightly

notifications:
    email: false
git:
  depth: 999999

before_install:
    - sudo apt-get install hdf5-tools
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.test("BigArrays")'
