language: julia
os:
    - linux
julia:
    - 0.5

notifications:
    email: false
git:
  depth: 999999

before_install:
    - sudo apt-get install hdf5-tools
script:
    - julia -e 'Pkg.clone("https://github.com/seung-lab/GSDicts.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/seung-lab/S3Dicts.jl.git")'
    - julia -e 'Pkg.clone(pwd()); Pkg.test("BigArrays")'
