language: julia
os:
    - linux
julia: 
    - 0.7
    - nightly

sudo: required 

notifications:
    email: false

script:
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("BigArrays")'

matrix:
    allow_failures:
        - julia: nightly
