language: julia
os:
    - linux
julia:
    - release
    - nightly


sudo: required 

notifications:
    email: false
git:
  depth: 999999

script:
    - sudo apt-get install -y hdf5-tools 
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("BigArrays")'

matrix:
    allow_failures:
        - julia: nightly
