language: julia
os:
    - linux
julia:
    - release
    - nightly

notifications:
    email: false
git:
  depth: 999999

before_install:
    - sudo apt-get install hdf5-tools
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.test("BigArrays")'

matrix:
    allow_failures:
        - julia: nightly
